namespace: aioue
name: network
version: 1.0.0

readme: README.md

authors:
  - Tom Paine (https://github.com/aioue)
  - Lenny Shirley (https://github.com/lennysh)

description: >-
  Discovers UniFi clients and optionally devices from a UniFi OS
  controller and provides them as Ansible inventory.

license:
  - GPL-3.0-or-later

tags:
  - unifi
  - inventory
  - network

dependencies: {}

repository: https://github.com/aioue/ansible-unifi-inventory
issues: https://github.com/aioue/ansible-unifi-inventory/issues

build_ignore:
  - ansible.cfg.example
  - '*.tar.gz'
